### ISSUE TITLE
Putting laptop to sleep breaks notebook refresh token

### ISSUE THREAD

**Issue by helgridly** [DataBiosphere/leonardo#206]
Reported by Josh Mandel @ Verily. He put his laptop to sleep, came back after lunch, and got the unauthed 401:

```
{"statusCode":401,"source":"leonardo","causes":[],"exceptionClass":"org.broadinstitute.dsde.workbench.leonardo.service.AuthorizationError","stackTrace":[],"message":"Your account is unauthorized"}
```

Presumably because his browser was asleep for longer than an hour, so when it tried to use its token to refresh the token, it was expired.

**Comment by rtitle** [comment]
See the wiki page here: https://github.com/DataBiosphere/leonardo/wiki/Connecting-to-a-Leo-Notebook

Proposed solution 3 should resolve this issue.

**Comment by katevoss** [comment]
There are two situations where a user can get this 401 page: when a user does not have access to the Notebook, and when a user has an expired refresh token. 

Part 1: UI
- [ ] Instead of 401 page, show "Sign-in with Google" button
- [ ] Future improvement: use FC's standard login page

Part 2: Refresh token
- [ ] Check if the user has valid token
- [ ] Check if the user has access to the notebook
- [ ] If the user does have access, refresh the token and set cookie when they sign in
   - [ ] With a valid token, redirect to the notebook

Part 3: Unauthorized
- [ ] If the user does not have access, redirect to the list of Workspaces with a message of why they don't see a notebook
  - [ ] Give action they can take to request access, or information about how to get access
