### ISSUE TITLE
Reduce time for cluster create requests

### ISSUE THREAD

**Issue by helgridly** [DataBiosphere/leonardo#215]
Note that this is different to #143 -- this ticket is about reducing the time it takes for the `HTTP PUT /cluster` request to return. @rtitle said there was some potential here around reducing the number of bucket setup calls we make to GCS.

AppEngine times out requests after 60s unconfigurably, so we should guarantee a response time lower than this.

**Comment by calbach** [comment]
+1. We're seeing pretty much 100% timeouts from the AoU workbench on cluster creates. Would be great if `createCluster` did minimal work during the request - pushing heavy lifting to be done asynchronously, then updated cluster status as it progresses (as it currently seems to do once dataproc initialization begins).

**Comment by rtitle** [comment]
Interesting - I know it takes a while but I don’t think I’ve seen it take more than 60 seconds. Maybe I’ll check some logs to see if there is anything else going on.

But yes, streamlining our Google calls and perhaps pushing more things over the async boundary should make this go faster.

**Comment by calbach** [comment]
So I checked on the actual deadline we're hitting here and it's 10sec. I'm not sure where in the stack that's being set and whether we control it, but I think expecting <10s latency for this kind of request is reasonable.

**Comment by rtitle** [comment]
Oh ok, I'm not surprised you're seeing timeouts then. :)

So we can speed this up in 2 ways:

1. Our bucket creation is inefficient: due to the Workbench Google library we're using, we're making separate API calls for `createBucket`, `setAccessControl`, `setDefaultObjectAccessControl`, and `setLifecycle`. But in fact this can all be done as part of the "create bucket" API call. So we can reduce our 8 calls to Google (because we create 2 buckets) to 2. 

2. Push more things over the async boundary. Perhaps only the auth check should be done synchronously; the bucket preparation and related setup can be done asynchronously by the ClusterMonitorActor. 

However neither of this will be done overnight -- it will probably be at least a couple weeks before this can be finished and deployed to production. In the short term, I feel like there must be a way to increase the deadline in AppEngine. Perhaps it's using a system-default setting of 10s but you can increase it per-request?

**Comment by calbach** [comment]
Thanks. Yes, we can definitely work around it for now - it's not blocking us by any means. I suspect we could increase the deadline on our side if this really started hurting but I haven't bothered looking into it yet.

**Comment by danqrodney** [comment]
When is this change going to hit production?

**Comment by rtitle** [comment]
The above change is already in prod (as of 4/10). I just timed a "PUT cluster" request in prod and it took ~7 seconds.

The other change mentioned (pushing more work over the async boundary) hasn't been started yet.

**Comment by danqrodney** [comment]
We are still seeing java.net.SocketTimeoutException when creating clusters using Leo prod. (At least sometimes; it's difficult to tell from our logs whether this is always happening or only sometimes.)

7 seconds is pretty close to 10 seconds, which I guess was the timeout? Should that be increased to something higher? (Where does that get configured?)

We can change our endpoint to kick off this call asynchronously and return immediately; or Leo could have the endpoint return immediately. There probably isn't much point in blocking for ~10 seconds when we know cluster initialization takes much longer than that.

**Comment by rtitle** [comment]
I think the 10 second timeout comes from AppEngine? I'm not sure how that is configured.

Agreed there is not much point in blocking for ~10 seconds. I think it would make sense for Leo to return immediately. It's just a matter of refactoring the code to do that. We'd also probably have to change our create cluster response to contain less information. (For backwards compatibility, we'll probably implement the async create as a _new_ API, and leave the existing one as-is.)
