### ISSUE TITLE
Add ability to set a default client ID at cluster creation time

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#289]
See https://github.com/DataBiosphere/leonardo/wiki/Connecting-to-a-Leo-Notebook, Proposed Change 1.

This was a request from AoU. We currently pass the client ID to the Jupyter notebook extension via a `postMessage` handshake. This allows us to dynamically set the client ID, and potentially use the same notebook from multiple portals. However it adds complexity and can be brittle as it relies on communication between tabs/windows. It would be nice to be able to specify a "default" client ID at cluster creation time. This would remove the need for `postMessage` entirely. (We could still keep the `postMessage` functionality in case the user needs to override it.)

**Comment by rtitle** [comment]
I met with with @zarsky-broad and we decided that Saturn wants to use this same approach. Bumping to P1 and moving to Ready.

**Comment by zarsky-broad** [comment]
To clarify: we are actually updating the cookie every 20 minutes.

**Comment by akarukappadath** [comment]
We just found out that we can't just add another field to the Cluster model in order to accommodate this because of a limit on the number of fields in spray-JSON and Scala functions. I'm working on modularizing the Cluster object (https://github.com/DataBiosphere/leonardo/issues/517) first to make room for more fields, and then will return to this ticket.

**Comment by zarsky-broad** [comment]
Is there no way to get around that? It seems like a crappy limitation.
