### ISSUE TITLE
Add an auth provider that checks permissions with a user's bearer token.

### ISSUE THREAD

**Issue by eap** [DataBiosphere/leonardo#399]
This is a proposal to add an authorization provider that could provide substantial benefits over the whitelist auth provider without having to depend on SAM.

Behavior of the auth provider:
  * `hasProjectPermission`
    - Resolve project permission using the user's bearer token to hit the resource-manager [testIamPermissions](https://cloud.google.com/resource-manager/reference/rest/v1beta1/projects/testIamPermissions) API. Trivially, the permission `resourcemanager.projects.setIamPolicy` could be checked, indicating that a user has owner or editor access on a project.
  * `hasNotebookClusterPermission`
    - Same as `hasProjectPermission`
  * filterUserVisibleClusters
    - Option 1: Use the bearer token to hit the [projects/list](https://cloud.google.com/resource-manager/reference/rest/v1beta1/projects/list) endpoint and compare projects (optionally, use labels to tag/filter projects where Leonardo is allowed).
    - Option 2: Iteratively use `testIamPermissions` on each project.
  * `notifyClusterCreated`/`Deleted`
    - NOP

Notes:
  * Leonardo admins using this provider would need to request the `https://www.googleapis.com/auth/cloudplatformprojects.readonly` scope during authentication.
  * Like the whitelist auth provider, this provider would not always prevent two users from accessing the same cluster since two or more users may be the admin of a GCP project. Unlike the whitelist provider, it would be possible for a user to truly isolate themselves by using a self-owned analysis project.

**Comment by rtitle** [comment]
Hi @eap,

I think this makes sense. So you'd use the `resourcemanager.projects.setIamPolicy` permission as a proxy for the project/cluster permission check. I think this permission exists in the Owner but not Editor role (Editor only has `getIamPolicy` unless I'm mistaken). Is it OK requiring that all Leo users have Owner role on the project?

You're correct to note that it would not prevent 2 users from accessing the same cluster -- but that may be fine since you're using the project-default service account (e.g. you're not putting user creds on the cluster like FC is doing).

Our Scala IAM wrapper code is here:

Interface: https://github.com/broadinstitute/workbench-libs/blob/develop/google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleIamDAO.scala
Implementation: https://github.com/broadinstitute/workbench-libs/blob/develop/google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleIamDAO.scala

I don't think we currently have a method that calls `testIamPermissions` but I would probably vote to add it to this class. Leo already depends on this library and uses it at runtime.

**Comment by rtitle** [comment]
I think this is done as of https://github.com/DataBiosphere/leonardo/pull/450. Closing this.
