### ISSUE TITLE
Leo still not working in an iframe

### ISSUE THREAD

**Issue by zarsky-broad** [DataBiosphere/leonardo#449]
There was [an attempt](https://github.com/DataBiosphere/leonardo/pull/442) to solve this previously, but I'm still seeing this in the headers when trying to open a notebook in an iframe:
```
content-security-policy: frame-ancestors 'self';
```

If necessary, we can explicitly whitelist hosts; that would be `http://localhost:3000` and `https://bvdp-saturn-dev.appspot.com/` on dev, and `https://bvdp-saturn-prod.appspot.com/` on prod.

**Comment by rtitle** [comment]
I think I found the root cause, it has to do with how we use both `webapp_settings` and `tornado_settings` in jupyter_notebook_config.py: 
https://github.com/DataBiosphere/leonardo/blob/develop/jupyter-docker/jupyter_notebook_config.py

It seems that webapp_settings was taking precedence. It worked when I did this:
```
c.NotebookApp.webapp_settings = {
    'static_url_prefix':'/notebooks/' + fragment + '/static/',
    'headers': {
        'Content-Security-Policy': "frame-ancestors 'self' 'https://*.appspot.com' 'localhost:3000' "
    }
}
```
Note I think it would be better to have a whitelist of hosts rather than ''. Something like the above should work.

For this ticket it would also be good to create a test which validates the correct `Content-Security-Policy` is set in the response.

**Comment by rtitle** [comment]
Another note: Jupyter actually complains that webapp_settings is deprecated. In jupyter.log
```
        webapp_settings is deprecated, use tornado_settings.
```
Maybe we should try moving `static_url_prefix` to tornado_settings as part of this ticket.

**Comment by rtitle** [comment]
Note: instead of https://*.appspot.com, it might be worth making this more specific to list: https://bvdp-saturn-prod.appspot.com and https://bvdp-saturn-dev.appspot.com.

Also as part of acceptance: check with security team if whitelisting these hosts is OK from their perspective.
