### ISSUE TITLE
Create a user script to install GATK

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#463]
In the absence of customizable docker containers, we should look at creating a user script which installs GATK to a cluster and allows use from within a notebook. The cluster already has Java installed, so we would need to:
   - download the GATK jar
   - install necessary python libraries (which ones)?

We can put the user script here: https://github.com/DataBiosphere/leonardo/tree/develop/jupyter-docker/user-scripts. It would also be nice to document the different user scripts we have available in a README.md in that directory.

**Comment by kyuksel** [comment]
[Hard Filtering tutorial](https://drive.google.com/drive/folders/1IHApTUhdlptMW7EDGFhmUUmB_f-JBu4K) can be used as an example of the kind of GATK workflows we'd like to enable on Notebooks via the script.

**Comment by abaumann** [comment]
do we want to tie this to a specific gatk version, or have it use latest?

**Comment by rtitle** [comment]
Probably the latest I imagine?

**Comment by kyuksel** [comment]
@tmm211 Is there a particular GATK version you need for the ASHG workshop?

**Comment by tmm211** [comment]
When you are ready to test the Hard Filtering tutorial, let me know so that we can generate the data for you. 
Is there a way for us to specify the version we want? I ask because say we are a month away from a workshop- we usually stick with whatever version of GATK we have then. If a new version gets released a few days before the workshop, we will not use it because we haven't had enough time to test all the commands with it. Also others who may use the script outside of the workshop may need a specific version...they won't always use the latest.

**Comment by abaumann** [comment]
I just have the GATK jars working - none of the python stuff if you need that.  right now it's a script you specify from a file in a bucket, so i can't make it dynamic enough to choose a version.  but it would be easy to cut a new version of the script right before the workshop

**Comment by tmm211** [comment]
ok that sounds good. I don't think we need the python stuff, but maybe I am missing something @rtitle ? The hard filtering tutorial actually requires some R packages, which I should be able to install after running this script, right?

**Comment by rtitle** [comment]
Yeah R (and python) packages should be installable in a notebook. Let's leave them out of the script unless we have a good reason to add them there. 

@abaumann once the script is in good shape can you add it to https://github.com/DataBiosphere/leonardo/tree/develop/jupyter-docker/user-scripts and make a PR? Thanks.

**Comment by abaumann** [comment]
I have the jar parts all set - I'll have tiffany test that out and then make a PR

**Comment by tmm211** [comment]
Testing...

**Comment by rtitle** [comment]
Interesting @tmm211, I'll take a look. One thing I noticed is you have `/home/jupyter-users/` in your code -- it should be `/home/jupyter-user/`. Not sure if that's related to the error though.

**Comment by tmm211** [comment]
@rtitle here are answers to your questions:
1. How did you install readr?  -- I thought it was already installed in the notebook. When I type library() it shows me a list of packages. readr was listed. I thought I activated it by calling library(readr)
2. When I run install.packages("readr")
I still get this error -> 
```
Installing package into ‘/home/jupyter-user/.rpackages’
(as ‘lib’ is unspecified)
Warning message in install.packages("readr"):
“installation of package ‘readr’ had non-zero exit status”
```

**Comment by tmm211** [comment]
Update:
See [workspace](https://portal.firecloud.org/#workspaces/broad-firecloud-dsp-pm/Workshop-Testing-Gatk-in-Notebooks) to view clusters.
Once I created a new cluster `gatk-testing-2`and a new notebook, I was able to install readr and get my R code working. Note, I did not use the gatk script in cluster creation.

Back in my old cluster `gatk-testing' I created a new notebook to see if there was an issue with starting my notebook out with a python 3 kernel then switching to R. Ruled this out because even in a new notebook on that cluster, I still got the issue above `“installation of package ‘readr’ had non-zero exit status”' then continued to have issues where the notebook didn't recognize readr.

So does this mean something is wrong with the cluster + gatk script? I could test by trying to create another new cluster + using the gatk script.

**Comment by tmm211** [comment]
PS: To give you context, I am active on this thread because we need to wrap up all changes to this tutorial by Aug 10 ideally.  The decisions to be made are around the design of the tutorial. Do we split this tutorial in parts so that users execute gatk commands in one notebook on one cluster and the straight R commands in another notebook on another cluster or can they both exist on the same cluster and in the same notebook (which would be ideal, but I am having problems with now). What happens when 30 people clone the featured workspace (holding the notebooks) and then run them? OR do we have folks upload the notebooks to a cluster instead?

**Comment by rtitle** [comment]
A few points:
1. `readr` is NOT currently installed by default in Leo clusters. However any clusters created after 7/31 ~5pm _will_ have readr installed by default as part of tidyverse.
2. readr can be installed manually via `install.packages("readr")`. This only needs to be done once. I wonder if the installation errors you're seeing is because it's already installed?
3. The error `shared object ‘readr.so’ not found` is strange to me -- it seems to imply that something was not installed correctly. I doubt it's related to the gatk user script -- that script just downloads and extracts a zip file, it doesn't do anything with R packages.
4. I also doubt that switching kernels has much to do with the `readr` error. However I would be careful in general with switching kernels within an existing notebook, because every time you switch your current session state is lost. For example if I have a python cell:
   ```
   foo = 'foo'
   ```
   then I switch to R and execute an R cell:
   ```
   bar <- "bar"
   ```
   then switch back to python, it would have no knowledge of the `foo` variable. Because of this, it might be more intuitive to have a separate notebook per language you are using.
5. Once the changes are in to store notebooks in a workspace (soon!), then cloning a featured workspace holding notebooks should work. Until then, users would need to manually upload notebooks to clusters. In either case, users would need to spin up their own clusters.

**Comment by tmm211** [comment]
Thanks for the notes Rob. 
I am making progress with the commands. Now a problem I am hitting is uploading a  .gz file on to the R kernel. When I click Upload, nothing happens. 
<img width="986" alt="screen shot 2018-08-05 at 3 04 31 pm" src="https://user-images.githubusercontent.com/13475639/43688991-4f3711e2-98c1-11e8-8878-e36f2351854f.png">

**Comment by tmm211** [comment]
Is this expected behavior for this file type? Do we know that certain file types won't be able to be uploaded to a cluster?

**Comment by rtitle** [comment]
@tmm211 that's weird, I just tested and I can upload .gz files. I wonder if it's related to the file size? If this is a lot of data would it be reasonable to upload to a bucket and access it from a notebook that way?

**Comment by tmm211** [comment]
good call. I will try that!

**Comment by tmm211** [comment]
Ok- all good! I am able to fully port over the tutorial now. Thanks for all of your help!! Last thing I wanted you to know was that when I tried to double click and open the .gz file I got an error. Not sure if that is intended or not.

**Comment by kyuksel** [comment]
@tmm211 That's great to hear.

> Last thing I wanted you to know was that when I tried to double click and open the .gz file I got an error. Not sure if that is intended or not.

Could you elaborate on what you were doing?

**Comment by tmm211** [comment]
Trying to open the file. I get this error
<img width="520" alt="screen shot 2018-08-08 at 6 15 52 pm" src="https://user-images.githubusercontent.com/13475639/43867428-342371d4-9b37-11e8-898f-9dab630776a7.png">

**Comment by kyuksel** [comment]
It turned out to be another manifestation of a [known bug](https://github.com/DataBiosphere/leonardo/issues/523) that we're hoping to fix soon.
