### ISSUE TITLE
Allow more recent version of pandas to be used

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#488]
The AoU pyclient is currently pegging their pandas requirements because of an old version installed in Leo. See https://github.com/all-of-us/pyclient/issues/27

1. what is the user error when pandas is upgraded from within a notebook?
2. can the Leo notebooks image include a more recent version of pandas?

**Comment by rtitle** [comment]
Note: the AoU pyclient has this requirement:
https://github.com/all-of-us/pyclient/blob/366f4c7b7f9200d52fdb91ef4d3219ee63c8ec03/py/requirements.txt
If upgrading past 0.21 it would break AoU. Should coordinate with AoU when working on this.

**Comment by rtitle** [comment]
@akarukappadath is running into some pandas issues for https://github.com/DataBiosphere/leonardo/issues/401 which might be related.

**Comment by rtitle** [comment]
May be relevant: https://github.com/pandas-dev/pandas/issues/20697

**Comment by rtitle** [comment]
According to the above python 3.4 is not supported by the latest versions of pandas. We might need to upgrade to python 3.5+ (a good idea anyway).

**Comment by akarukappadath** [comment]
As Rob mentioned above, python 3.4 isn't supported by the latest version of pandas. To upgrade pandas, we would need to upgrade debian jessie to stretch (https://github.com/DataBiosphere/leonardo/issues/445) in order to upgrade to Python 3.5. However, this step means that we need a newer Spark (currently 2.0.2), which would also imply upgrading Dataproc to 1.2 (https://github.com/DataBiosphere/leonardo/issues/144) and Hail to 0.2 (https://github.com/DataBiosphere/leonardo/issues/193). Since all of these are interwoven, it would likely be smartest (and easiest) to upgrade all of these at the same time.

**Comment by danqrodney** [comment]
@rtitle  @akarukappadath 

(CC @calbach)

Is there an update on when this upgrade will occur? (I'm running into more problems with running an old version of Pandas...)

**Comment by akarukappadath** [comment]
@danqrodney we're currently working on this, and hoping to get it out by this quarter!
