### ISSUE TITLE
Embedding notebooks in Iframe

### ISSUE THREAD

**Issue by YanayRosen** [DataBiosphere/leonardo#510]
I'm trying to embed a notebook in an iframe, from notebooks.firecloud

I get a content security policy violation that it violates frame-ancestors csp.

I'm not sure this is avoidable in local development. I think I might have to start a local Leonardo server- - but I'm not sure how to after following the readme.

**Comment by rtitle** [comment]
Hi @YanayRosen,

We actually set CSP in Jupyter to allow embedding in an iframe for a whitelist of hosts. This is the current list:

https://github.com/DataBiosphere/leonardo/blob/develop/jupyter-docker/jupyter_notebook_config.py#L34

If you can let us know the hostnames you'd like to add for SCP, we can add them to the list. We can also add https://localhost:443 for local development.

This config gets put in the Docker image which gets installed on Leonardo clusters. Therefore it requires a prod release to take effect (which usually happens on Tuesdays). In the meantime I can update CSP on an Leo-created clusters you have -- just let me know the project and cluster names.

Deploying a local Leo is likely more trouble than it's worth in this case because it would involve Docker shennanigans either way -- but we could also help with that if needed.

**Comment by MatthewBemis** [comment]
Closed as it appears this is no longer a need
