### ISSUE TITLE
Increase akka-http content-length limit

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#523]
@mbookman encountered 502s when saving a notebook with output. @rtitle investigated and found this error in the Leo logs:

```
[ERROR] [22:38:57.287] [leonardo-akka.actor.default-dispatcher-179401] o.b.d.w.l.service.ProxyService - Error occurred in Jupyter proxy
akka.http.scaladsl.model.EntityStreamSizeException: EntityStreamSizeException: actual entity size (Some(10963308)) exceeded content length limit (8388608 bytes)! You can configure this by setting `akka.http.[server|client].parsing.max-content-length` or calling `HttpEntity.withSizeLimit` before materializing the dataBytes stream.
```

The 8MB content length limit is probably an akka-http default. We should increase it, especially considering notebooks can be large given they can have images, etc.

**Comment by kyuksel** [comment]
Allow 100MB

**Comment by rtitle** [comment]
Maybe a conservative approach would be to double the current 8M to 16M.

**Comment by mbookman** [comment]
FWIW, I wanted to start using [facets](https://github.com/PAIR-code/facets) for interactive visualizations in my notebook, so I brought in the first two cells from this notebook to a brand new test notebook in Saturn:

https://colab.sandbox.google.com/drive/1QrcuNHJnL3TBzcFV-0yw6y3wWmSWv_gM#scrollTo=XtOzRy8Z3M36

It runs and I see the visualization, but I get the "Bad Gateway" error on save unless I clear the output of the second cell.

**Comment by kyuksel** [comment]
@mbookman Thank you very much for the input. How much data does the total of the two cells amount to? Do you expect to add more cells like those in the future? If so, how much data do you think they all may result in?

**Comment by mbookman** [comment]
Good question.

I just now saved the sample notebook:

https://colab.sandbox.google.com/drive/1QrcuNHJnL3TBzcFV-0yw6y3wWmSWv_gM#scrollTo=XtOzRy8Z3M36

to ipynb locally and it was 11.6 MB. When I look at the file, I can see that almost all of that is just the data. A problem is that the encoding is very verbose. Since it is json, all the "column headers" are repeated as field names for each record.

When I curl the data file (https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data), it is 3.8 MB.

This seems like a modest sized dataset that one might want to visualize in a notebook.

**Comment by kyuksel** [comment]
The same issue also causes the error below when opening files on the Jupyter Notebook UI:

![jupyter_file_open_error](https://user-images.githubusercontent.com/5438223/43919492-11ea5c60-9be4-11e8-9e00-02067e75147b.png)

**Comment by rtitle** [comment]
To resolve this:
* increase the content length limit in akka config
* add an auto-test which tries to open a file >8mb and verifies that it works
