### ISSUE TITLE
Nuke buckets in broad-dsde-prod after cluster is done

### ISSUE THREAD

**Issue by davidbernick** [DataBiosphere/leonardo#536]
And clean up existant buckets. @vkumra-broad and @kyuksel know what I'm talking about. They can elaborate.

**Comment by kyuksel** [comment]
@davidbernick Would you say that, not creating the `init-bucket`s in `broad-dsde-proj` at the first place is the ideal way to go but deleting those buckets after a cluster is removed and deleting the buckets orphaned by then are an acceptable solution?

**Comment by rtitle** [comment]
I think I remember some context here.

We create these buckets in broad-dsde-* because they contain Leo secrets (certs, etc) which we don't want to be viewable by the user. Originally, we were deleting these buckets after the cluster was initialized. However, this caused issues with preemptibles -- since new preemptibles may come online at any time they need access to the init bucket even after the cluster is initialized. So we stopped deleting these buckets entirely. A reasonable solution (I'm not sure why this wasn't done) would be to delete these buckets when the cluster is _deleted_.

So I propose the following:
1. Run a script or something to clean up existing buckets for any deleted clusters
2. Change Leo code to delete init buckets when a cluster is deleted

I'm still a bit hesitant to put these buckets in users' billing projects because they contain secrets/certs which we only want viewable by Leo.

**Comment by rtitle** [comment]
@MatthewBemis just following up, what's the status of cleaning up the old `leoinit` buckets? cc @kcibul

**Comment by MatthewBemis** [comment]
i ran it in broad-dsde-dev and broad-dsde-alpha so far. it took a while, but cleaned up buckets for ~24,000 deleted clusters. i wanted to make sure i could run it in prod in one working day so it didn't get broken up.

i will prioritize running it in broad-dsde-prod tomorrow morning. then all of the associated cleanup should be complete aside from broad-dsde-qa but we may need to handle that differently since there's no persistent db to go off of

**Comment by MatthewBemis** [comment]
this is done now
