### ISSUE TITLE
Leonardo returns x-frame-options: SAMEORIGIN

### ISSUE THREAD

**Issue by zarsky-broad** [DataBiosphere/leonardo#544]
While this doesn't cause an issue in Chrome, Safari prevents Saturn from rendering Leo in an iFrame because of this.

**Comment by rtitle** [comment]
Seems like this is affecting Chrome now.

**Comment by rtitle** [comment]
To fix this we could configure x-frame-options the same way we configure CSP:

https://github.com/DataBiosphere/leonardo/blob/develop/src/main/resources/reference.conf#L101

**Comment by zarsky-broad** [comment]
Would it be possible to unset this entirely and allow Leo to be embedded anywhere? We need to be able to open it from within our deployed PR sites.

**Comment by bradtaylor** [comment]
@zarsky-broad's request is important because it allows us to build/test our software. If we can't unset it entirely, could we whitelist a whole domain, or something? Our ability to test PRs is important for our development process

**Comment by zarsky-broad** [comment]
@rtitle Could [this](https://github.com/broadinstitute/firecloud-develop/blob/3e24356fed3e955edb10f2f8cb15521d0e8d2147/base-configs/leonardo/site.conf.ctmpl#L16) be to blame?

**Comment by rtitle** [comment]
A few comments here.

1. @zarsky-broad ah yeah, site.conf is probably what is setting this header, not Jupyter. We could probably just unset it in apache conf. I want some security minded folks (cc @adrazhi) to weigh in though: are there any issues with the Leo apache proxy always unsetting the `X-Frame-Options` response header (thus allowing any site to embed a notebook in an iframe)?

2. I'm a bit confused on how `X-Frame-Options` relates to `Content-Security-Policy` `frame-ancestors`. Can anyone enlighten me? Our CSP currently whitelists Saturn dev and prod URLs. But it does NOT include PR URLs which look like https://pr-something-dot-saturn-dev.appspot.com. So even if we unset `X-Frame-Options` then Saturn PR URLs still wouldn't work because of CSP right?

3. CSP doesn't let you put wildcards anywhere in the URL -- you can only wildcard full domains or subdomains. E.g. `https://*.appspot.com` is fine but `https://*saturn*.appspot.com` is not. I think that's why we excluded the PR URLs from the whitelist, because we can't predict what the top-level-domain will be. We are hesitant to just open up CSP to the world (@adrazhi was involved in this too). @bradtaylor @zarsky-broad could Saturn think about using a domain other than `.appspot.com`? I think it'd be easier to whitelist something like `*.saturn.org`.

**Comment by zarsky-broad** [comment]
Re: the above

> are there any issues with the Leo apache proxy always unsetting the X-Frame-Options response header (thus allowing any site to embed a notebook in an iframe)?

@adrazhi I'd love if we could do this. iFrames are totally walled off from their parent windows, and Leo access still requires that the cookie be set, so what harm could opening this up do?

> So even if we unset X-Frame-Options then Saturn PR URLs still wouldn't work because of CSP right?

@rtitle Correct. However, it would make embeds work _at all_ in Safari on local/dev/prod, which they currently don't.

> could Saturn think about using a domain other than .appspot.com?

@rtitle I suspect people would be hesitant to do this until we have our real name, which I believe is coming soon (TM)...

**Comment by adrazhi** [comment]
@rtitle @zarsky-broad Yeah so the idea behind setting the `X-Frame-Options` header is to prevent clickjacking attacks. If you unset that, you can use CSP's defense mechanisms via `frame-ancestors` which allows the authorization of multiple domains unlike 'X-Frame-Options` which allows only one. I think that would solve the issue introduced by the apache conf SAMEORIGIN, while still protecting against clickjacking. Does that make sense?

Also take into account that frame-ancestors does not fall back to the default sources when the directive is not defined (like `form-action` and `base-uri`). Which means, such policy

`Content-Security-Policy: default-src 'none';`
will still allow the resource to be framed from anywhere and you should explicitly specify frame-ancestors directive:

`Content-Security-Policy: default-src 'none'; frame-ancestors 'none'`

**Comment by zarsky-broad** [comment]
@adrazhi wouldn't `frame-ancestors 'none'` prevent us from embedding Leo as an iframe, though?

**Comment by adrazhi** [comment]
@zarsky-broad That was the example to show what would happen in a scenario where frame-ancestors don't fall back to the default sources. 

You'd probably solve your issue if you do something similar to: https://github.com/DataBiosphere/leonardo/blob/develop/src/main/resources/reference.conf#L103

**Comment by adrazhi** [comment]
@zarsky-broad `frame-ancestors` allow for the authorization of multiple domains, a flexibility that `X-Frame_Options` do not grant.

**Comment by rtitle** [comment]
@sharmatime I wanted to put this on your radar for a future refinement. This ticket is the only thing blocking Terra from working on Safari, so would be nice to push it through at some point.

Technically, re-reading the above convo it sounds like we could resolve this by removing `X-Frame-Options` from the apache proxy, and setting it in Leo code in a similar way as `Content-Security-Policy/frame-ancestors`. We can refine further but it doesn't seem like a large amount of work.
