### ISSUE TITLE
New FireCloud UI doesn't surface createCluster API errors

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#582]
To repro:
1. create a cluster with invalid characters (such as capital letters)
2. cluster spins in Creating status forever
3. refresh the page
4. cluster disappears

Instead of moving to Creating status, the error from Leo should be displayed to the user.

**Comment by kyuksel** [comment]
@rtitle Was this hit using the old (non-async) cluster creation API? The reason I'm asking is that, we have a behaviour in the new (async) API that could cause the behaviour you described. With the async API, when a user specifies an invalid cluster name, the API call is still completed with `202` since we don't know, at the completion time, of the naming error we end up getting from Google. With the non-async API, we return a `500` with the appropriate error message, which should be sufficient for the UI to act accordingly. I filed a ticket (#590) for the backend bug.

**Comment by rtitle** [comment]
This was using the new async API.

**Comment by rtitle** [comment]
Addressed in PR: https://github.com/broadinstitute/firecloud-ui/pull/1423
