### ISSUE TITLE
Consider a tighter deadline for dataproc cluster creation

### ISSUE THREAD

**Issue by calbach** [DataBiosphere/leonardo#729]
Yesterday AoU saw a cluster sitting in the "creating" state for ~1 hour. Per @vkumra-broad, this was all dataproc cluster creation and eventually dataproc returned an error of `Timeout waiting for instance all-of-us-m to report in.`. The cluster I believe then entered the error state which was detected for deletion/retry by AoU, which is what we wanted in this case. The user was stuck trying to open a notebook for this entire hour.

I don't think we've seen this before (cluster creation time would be a good thing to get metrics on), but Leo should consider setting a shorter deadline, e.g. 20m or 30m, as I'd guess anything over this time limit is likely to fail anyways.

**Comment by sharmatime** [comment]
CH does that mean that the issue for cluster creation was on the dataproc end, and to protect users from this we could implement a tighter deadline for dataproc cluster creation?

**Comment by calbach** [comment]
@sharmatime this is my understanding, yes.

**Comment by vkumra-broad** [comment]
I don't see any config that we can set for a tighter dataproc creation deadline besides the NodeInitialization timeout which we currently set to 10 mins. https://cloud.google.com/dataproc/docs/reference/rest/v1beta2/ClusterConfig

We would need to change leo functionality to handle this or have google expose this config. Since this is more work than initially estimated I am moving this to the backlog to be reprioritized and estimated. There have been two instances of this error in leo prod.

**Comment by MatthewBemis** [comment]
This may be covered by https://github.com/DataBiosphere/leonardo/issues/730, which is in progress
