### ISSUE TITLE
Verify required permission for Leo SA

### ISSUE THREAD

**Issue by vkumra-broad** [DataBiosphere/leonardo#806]
Bernick pinged the #dsp-infosec-champions room in slack asking that we look into the service specific Service Accounts to verify what permissions they actually need.

**Comment by davidbernick** [comment]
This is not new -- I asked about this in November. Do we have an official answer?

**Comment by rtitle** [comment]
The ask here is what permissions the Leo SA needs in broad-dsde-prod, correct? I believe we need storage admin, because we create buckets in broad-dsde-prod. Other operations are all done in users' billing projects.

We may be able to test this:
1. Create a SA in broad-dsde-dev
2. Deploy Leo to a fiab. Change `leonardo.conf` to point to the above SA
3. Play with IAM roles for the above SA until we find the minimal set that works

**Comment by davidbernick** [comment]
you probably also need SQLProxy rights (i think it's called SQLClient in
IAM).

**Comment by vkumra-broad** [comment]
Tested in dev: `Storage Admin` and `CloudSQL Client` are the only permissions that leo service account needs.

**Comment by vkumra-broad** [comment]
Also needs `Dataproc Viewer` permission.
