### ISSUE TITLE
Newly created cluster is absent from list clusters response

### ISSUE THREAD

**Issue by MatthewBemis** [DataBiosphere/leonardo#821]
Hi Leo folks: A while back we chatted about a slight lag between requesting a status change on a cluster and seeing that change reflected back. I just observed this happening while creating a cluster. Here's a successful 'create', followed by a 'list' that shows no results. The cluster does show up in the list eventually, but it takes at least several seconds.

I don't remember exactly where we left this, but it would be great to look into the cause when you have some bandwidth. Thanks!

**Comment by sharmatime** [comment]
From Rob:
**List clusters returns stale results due to Sam caching** 
 - Brett has complained about this, and Rob’s experienced this in UI
 - In UI, if you hit the play button, it doesn’t change to creating or starting for some time 
 - UI is asking Leo for status, but Leo is returning stale results
 - Rob suspects SAM caching at the root of this

User outcome:
 - The User should observe the status change without lag time, so they are not confused about the state of their cluster

**Comment by rtitle** [comment]
This was released last week. Closing.
